name: cti
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'
dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.1
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.2
  flutter_styled_toast: ^2.2.1
  intl: ^0.18.1
  file_picker: ^8.0.0+1
  gallery_saver: ^2.3.2
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
 